Repository wanessabezerra/Taskiano, pull requests merged in 2021-08, with the labels that each got.

#124 Rest api backend2
  taskiano/backend/task/migrations/0001_initial.py
  taskiano/backend/task/models.py
  taskiano/backend/taskiano/urls.py
Labels: enhancement

#129 Doc/contagem ppf
  docs/doc-apf.md
Labels: documentation

#130 Frontend: Task Creator component added
  .gitignore
  docs/doc-apf.md
  taskiano/frontend/.editorconfig
  taskiano/frontend/components/ClockTimer/index.tsx
  taskiano/frontend/components/ClockTimer/styles.module.scss
  taskiano/frontend/components/Compass/WeekdayBar/index.tsx
  taskiano/frontend/components/Compass/WeekdayBar/styles.module.scss
  taskiano/frontend/components/Compass/components/Bar.styles.tsx
  taskiano/frontend/components/CreateTask/Fields/index.tsx
  taskiano/frontend/components/CreateTask/Fields/styles.module.scss
  taskiano/frontend/components/CreateTask/MarkdownPreview/MarkdownPreview.tsx
  taskiano/frontend/components/CreateTask/MarkdownPreview/styles.module.scss
  taskiano/frontend/components/CreateTask/MarkdownWrapper.jsx
  taskiano/frontend/components/CreateTask/index.tsx
  taskiano/frontend/components/CreateTask/styles.module.scss
  taskiano/frontend/components/Modal/index.tsx
  taskiano/frontend/components/Modal/styles.module.scss
  taskiano/frontend/components/ProjectWidget/ProjectStatus/index.tsx
  taskiano/frontend/components/ProjectWidget/ProjectStatus/styles.module.scss
  taskiano/frontend/components/ProjectWidget/index.tsx
  taskiano/frontend/components/ProjectWidget/styles.module.scss
  taskiano/frontend/components/Sidebar/styles.module.scss
  taskiano/frontend/components/Task/index.tsx
  taskiano/frontend/components/Task/styles.module.scss
  taskiano/frontend/components/TasksStatus/styles.module.scss
  taskiano/frontend/components/Timers/Selector/styles.module.scss
  taskiano/frontend/components/Timers/index.tsx
  taskiano/frontend/components/Timers/styles.module.scss
  taskiano/frontend/components/ToogleButton/index.tsx
  taskiano/frontend/components/ToogleButton/styles.module.scss
  taskiano/frontend/components/Topbar/index.tsx
  taskiano/frontend/components/Topbar/styles.module.scss
  taskiano/frontend/components/UserScore/styles.module.scss
  taskiano/frontend/package.json
  taskiano/frontend/pages/home/GlobalStatus/styles.module.scss
  taskiano/frontend/pages/home/Projects/index.tsx
  taskiano/frontend/pages/home/Projects/styles.module.scss
  taskiano/frontend/pages/home/index.tsx
  taskiano/frontend/pages/home/styles.module.scss
  taskiano/frontend/services/api.ts
  taskiano/frontend/styles/globals.scss
  taskiano/frontend/styles/variables.scss
  taskiano/frontend/styles/variables.ts
  taskiano/frontend/tsconfig.json
  taskiano/frontend/yarn.lock
Labels: enhancement

#131 Views django
  taskiano/backend/task/models.py
  taskiano/backend/task/urls.py
  taskiano/backend/taskiano/settings.py
Labels: documentation

#132 Backend deploy
  .gitignore
  taskiano/backend/Pipfile
  taskiano/backend/Pipfile.lock
  taskiano/backend/Procfile
  taskiano/backend/README.md
  taskiano/backend/docs/heroku.md
  taskiano/backend/docs/local.md
  taskiano/backend/requirements.txt
  taskiano/backend/task/models.py
  taskiano/backend/task/urls.py
  taskiano/backend/taskiano/settings.py
Labels: documentation, enhancement, wontfix

#135 Feat/issue125: deploy and integrate
  taskiano/frontend/@types/Task.ts
  taskiano/frontend/components/CreateTask/index.tsx
  taskiano/frontend/components/CreateTask/styles.module.scss
  taskiano/frontend/components/MarkdownPreview/index.tsx
  taskiano/frontend/components/MarkdownPreview/styles.module.scss
  taskiano/frontend/components/MarkdownWrapper/index.jsx
  taskiano/frontend/components/Modal/index.tsx
  taskiano/frontend/components/Modal/styles.module.scss
  taskiano/frontend/components/ProjectWidget/index.tsx
  taskiano/frontend/components/Task/index.tsx
  taskiano/frontend/components/Task/styles.module.scss
  taskiano/frontend/pages/home/Projects/index.tsx
  taskiano/frontend/services/api.ts
  taskiano/frontend/utils/index.ts
Labels: enhancement

#146 Update README.md
  README.md
Labels: documentation

#147 :memo: Causa do desespero de 3 horas #34
  taskiano/backend/taskiano/urls.py
Labels: enhancement

#159 Rotas
  taskiano/backend/requirements.txt
  taskiano/backend/task/api/viewsets.py
  taskiano/backend/taskiano/settings.py
Labels: enhancement

#161 Fixes/frontend
  taskiano/frontend/components/ClockTimer/index.tsx
  taskiano/frontend/components/Compass/WeekdayBar/index.tsx
  taskiano/frontend/components/Compass/components/Bar.styles.tsx
  taskiano/frontend/components/ProjectsWidget/Widget/ProjectStatus/index.tsx
  taskiano/frontend/components/Timers/index.tsx
  taskiano/frontend/pages/api/hello.ts
  taskiano/frontend/styles/colors.ts
Labels: wontfix

#166 Fixes/frontend
  taskiano/frontend/components/Carousel/PageState.tsx
  taskiano/frontend/components/Carousel/index.tsx
  taskiano/frontend/components/Carousel/styles.module.scss
  taskiano/frontend/components/Checkbox/index.tsx
  taskiano/frontend/components/Checkbox/styles.module.scss
  taskiano/frontend/components/Modal/index.tsx
  taskiano/frontend/components/Modal/styles.module.scss
  taskiano/frontend/components/ProjectsList/Table/index.tsx
  taskiano/frontend/components/ProjectsList/index.tsx
  taskiano/frontend/components/Task/index.tsx
  taskiano/frontend/components/Task/styles.module.scss
  taskiano/frontend/components/TasksStatus/index.tsx
  taskiano/frontend/components/Timers/RenderTime/styles.module.scss
  taskiano/frontend/contexts/ProjectsContext/Provider.ts
  taskiano/frontend/contexts/ProjectsContext/index.tsx
  taskiano/frontend/pages/home/Projects/index.tsx
  taskiano/frontend/pages/home/Projects/styles.module.scss
  taskiano/frontend/services/api/Task.rest.ts
  taskiano/frontend/tsconfig.json
Labels: bug, help wanted, wontfix

#167 Feat/login page
  taskiano/frontend/assets/icons/logo_primary.svg
  taskiano/frontend/package.json
  taskiano/frontend/pages/index.tsx
  taskiano/frontend/styles/Login.module.scss
  taskiano/frontend/yarn.lock
Labels: enhancement

#172 :memo: Adição da Ce e Atualização da Contagem Detalhada #32 #170 #171
  docs/doc-apf.md
Labels: documentation

#173 :hammer: mudança em status #34 #112
  taskiano/backend/task/models.py
Labels: enhancement
