Repository wanessabezerra/Taskiano, pull requests merged in 2021-07, with the labels that each got.

#28 :memo: Update task's to it-02
  docs/tarefas.md
Labels: documentation

#36 :sparkles: Add brM3 model #35
  docs/models/entity_relationship.brM3
Labels: documentation

#39 Tarefa 06 - Revisar modelo de entidade relacionamento - [Validação]
  docs/images/entity_relationship_model.png
  docs/models/entity_relationship.brM3
Labels: documentation, help wanted

#45 Describe User US #41
  docs/doc-userstories.md
Labels: documentation

#47 Add arch model to docs #46
  docs/doc-arq.md
Labels: documentation

#44 Add avatarUrl attr to User entity #42 #43
  docs/doc-modelos.md
  docs/images/entity_relationship_model.png
  docs/models/entity_relationship.brM3
Labels: documentation

#52 Refactor doc-arq structure and index #51
  docs/doc-arq.md
Labels: documentation

#53 Add techs description to doc-arq 4.1 #50
  docs/doc-arq.md
Labels: documentation

#56 Add revision tag to US User #55
  docs/doc-userstories.md
Labels: documentation, help wanted

#59 Add revisions from last changes #58
  docs/doc-arq.md
Labels: documentation, help wanted

#60 Add arch image and description to doc-arq #57
  docs/doc-arq.md
  docs/images/arch.png
Labels: documentation

#62 Doc user task
  docs/doc-userstories.md
Labels: documentation

#63 Add doc-arq document description #61
  docs/doc-arq.md
Labels: documentation

#66 Add architectural mechanisms and topic description #64
  docs/doc-arq.md
Labels: documentation

#69 Add us tests doc #65
  docs/doc-us-test-result.md
Labels: documentation

#75 Add rev tag to doc-arq #74
  docs/doc-arq.md
Labels: documentation

#76 Add design decisions topic in doc-arq #70
  docs/doc-arq.md
Labels: documentation

#78 Remove ambiguity from user story files #77
  docs/doc-us-specs.md
Labels: documentation, help wanted

#80 Add acceptance tests to US01 #79
  docs/doc-userstories.md
Labels: documentation

#82 :memo: Refactor of doc-us-test-result to doc-us-tests with markdown #81
  docs/doc-us-test-result.md
  docs/doc-us-tests.md
Labels: documentation, help wanted

#84 Add doc-us-tests link and remove old ambiguity of us #83
  README.md
Labels: documentation

#85 Add doc-apf initial doc #72
  README.md
  docs/doc-apf.md
Labels: documentation

#87 Descriçao projeto
  docs/doc-userstories.md
  docs/doc-visao.md
Labels: documentation

#88 Correção de indentação
  docs/doc-visao.md
Labels: documentation, wontfix

#90 Update doc-apf structure and Add Indicative Count (CI)
  docs/doc-apf.md
Labels: documentation

#92 Add doc-project-charter document #33 #91
  docs/doc-project-charter.md
Labels: documentation

#94 Update readme with project charter doc
  README.md
Labels: documentation

#100 Requisitos não funcionais
  docs/doc-arq.md
Labels: documentation

#102 Arq desc componente
  docs/doc-arq.md
  docs/images/diagrama_uml.png
Labels: documentation

#103 Update doc-arq.md
  docs/doc-arq.md
Labels: documentation

#104 Update README.md
  README.md
Labels: documentation, enhancement

#109 Hotfix Ci
  .gitignore
  docs/doc-apf.md
  docs/doc-us-test-result.md
Labels: documentation

#110 Detalhando validação
  docs/doc-arq.md
Labels: documentation

#111 Apf task
  docs/doc-apf.md
Labels: documentation

#114 Refactor Cd table #113
  docs/doc-apf.md
Labels: wontfix

#116 Add frontend side's and top base
  taskiano/frontend/.babelrc
  taskiano/frontend/assets/icons/logo_primary.svg
  taskiano/frontend/components/Card/index.tsx
  taskiano/frontend/components/Carousel/PageIndicator.tsx
  taskiano/frontend/components/Carousel/components/CarouselContainer.styles.tsx
  taskiano/frontend/components/Carousel/components/Indicator.styles.tsx
  taskiano/frontend/components/Carousel/index.tsx
  taskiano/frontend/components/Carousel/styles.module.scss
  taskiano/frontend/components/Compass/WeekdayBar.tsx
  taskiano/frontend/components/Compass/components/Bar.styles.tsx
  taskiano/frontend/components/Compass/index.tsx
  taskiano/frontend/components/Compass/styles.module.scss
  taskiano/frontend/components/Compass/types/index.d.ts
  taskiano/frontend/components/Compass/utils/index.ts
  taskiano/frontend/components/Grid/index.tsx
  taskiano/frontend/components/Sidebar/index.tsx
  taskiano/frontend/components/Sidebar/styles.module.scss
  taskiano/frontend/components/Timers/RemainsFormat.tsx
  taskiano/frontend/components/Timers/components/TaskTag.style.tsx
  taskiano/frontend/components/Timers/index.tsx
  taskiano/frontend/components/Timers/styles.module.scss
  taskiano/frontend/components/Topbar/index.tsx
  taskiano/frontend/components/Topbar/styles.module.scss
  taskiano/frontend/components/User/index.tsx
  taskiano/frontend/contexts/HelloContext.tsx
  taskiano/frontend/package.json
  taskiano/frontend/pages/index.tsx
  taskiano/frontend/public/android-chrome-192x192.png
  taskiano/frontend/public/android-chrome-512x512.png
  taskiano/frontend/public/apple-touch-icon-precomposed.png
  taskiano/frontend/public/apple-touch-icon.png
  taskiano/frontend/public/browserconfig.xml
  taskiano/frontend/public/favicon-16x16.png
  taskiano/frontend/public/favicon-32x32.png
  taskiano/frontend/public/favicon.ico
  taskiano/frontend/public/mstile-144x144.png
  taskiano/frontend/public/mstile-150x150.png
  taskiano/frontend/public/mstile-310x150.png
  taskiano/frontend/public/mstile-310x310.png
  taskiano/frontend/public/mstile-70x70.png
  taskiano/frontend/public/safari-pinned-tab.svg
  taskiano/frontend/public/site.webmanifest
  taskiano/frontend/public/vercel.svg
  taskiano/frontend/styles/globals.scss
  taskiano/frontend/styles/pages/Home.module.scss
  taskiano/frontend/yarn.lock
Labels: enhancement

#117 Refactor base code and add global status
  taskiano/frontend/@types/Task.ts
  taskiano/frontend/@types/Weekday.ts
  taskiano/frontend/@types/WeekdayPercent.ts
  taskiano/frontend/@types/index.ts
  taskiano/frontend/assets/icons/index.tsx
  taskiano/frontend/components/Compass/WeekdayBar/index.tsx
  taskiano/frontend/components/Compass/WeekdayBar/styles.module.scss
  taskiano/frontend/components/Compass/index.tsx
  taskiano/frontend/components/Compass/styles.module.scss
  taskiano/frontend/components/Compass/utils/index.ts
  taskiano/frontend/components/Task/index.tsx
  taskiano/frontend/components/Task/styles.module.scss
  taskiano/frontend/components/TasksStatus/index.tsx
  taskiano/frontend/components/TasksStatus/styles.module.scss
  taskiano/frontend/components/Timers/RemainsFormat.tsx
  taskiano/frontend/components/Timers/RenderTime/index.tsx
  taskiano/frontend/components/Timers/RenderTime/styles.module.scss
  taskiano/frontend/components/Timers/Selector/index.tsx
  taskiano/frontend/components/Timers/Selector/styles.module.scss
  taskiano/frontend/components/Timers/TaskTag/index.style.tsx
  taskiano/frontend/components/Timers/index.tsx
  taskiano/frontend/components/Timers/styles.module.scss
  taskiano/frontend/components/UserScore/index.tsx
  taskiano/frontend/components/UserScore/styles.module.scss
  taskiano/frontend/contexts/HelloContext.tsx
  taskiano/frontend/next.config.js
  taskiano/frontend/pages/home/GlobalStatus/index.tsx
  taskiano/frontend/pages/home/GlobalStatus/styles.module.scss
  taskiano/frontend/pages/home/Projects/index.tsx
  taskiano/frontend/pages/home/Projects/styles.module.scss
  taskiano/frontend/pages/home/index.tsx
  taskiano/frontend/pages/home/styles.module.scss
  taskiano/frontend/services/api.ts
  taskiano/frontend/shared/Carousel/PageIndicator.tsx
  taskiano/frontend/shared/Carousel/components/CarouselContainer.styles.tsx
  taskiano/frontend/shared/Carousel/components/Indicator.styles.tsx
  taskiano/frontend/shared/Carousel/index.tsx
  taskiano/frontend/shared/Carousel/styles.module.scss
  taskiano/frontend/shared/ClockTimer/index.style.tsx
  taskiano/frontend/styles/components/Card.module.scss
  taskiano/frontend/styles/components/Grid.module.scss
  taskiano/frontend/styles/components/User.module.scss
  taskiano/frontend/utils/index.ts
Labels: enhancement

#122 Rest api backend
  taskiano/backend/task/__init__.py
  taskiano/backend/task/admin.py
  taskiano/backend/task/api/serializers.py
  taskiano/backend/task/api/viewsets.py
  taskiano/backend/task/apps.py
  taskiano/backend/task/migrations/0001_initial.py
  taskiano/backend/task/migrations/__init__.py
  taskiano/backend/task/models.py
  taskiano/backend/task/tests.py
  taskiano/backend/task/views.py
  taskiano/backend/taskiano/settings.py
  taskiano/backend/taskiano/urls.py
Labels: enhancement
