Repository wanessabezerra/Taskiano, pull requests merged in 2021-09, with the labels that each got.

#177 :memo: Alteração nas datas do plano de iteração
  docs/doc-iteracao.md
Labels: documentation

#189 Atualizacao
  README.md
  docs/doc-arq.md
  docs/doc-iteracao.md
  docs/doc-project-charter.md
  docs/doc-us-test-result.md
  docs/doc-us-tests.md
  docs/doc-userstories.md
  docs/images/diagrama_uml.png
Labels: documentation

#193 Adição de teste de user #188 #34
  taskiano/backend/api/tests.py
Labels: enhancement

#192 Update: set correction for backend endpoint
  taskiano/frontend/services/api/index.ts
Labels: bug
